### ISSUE TITLE
non ASCII glyphs breaks all fonts

### ISSUE THREAD

**Issue by GazziFX** [vape/Imui#11]
When I open demo scene and type russian letters in text field, they appears normal but when I stop playmode a lot of errors popup and even Package Manager unable to render text. Similar error can also occur in `TextDrawer` constructor
```
MissingReferenceException: The object of type 'Texture2D' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Texture2D.Apply (System.Boolean updateMipmaps, System.Boolean makeNoLongerReadable) (at <91dc399f41a440558c716315c7e834ab>:0)
UnityEngine.TextCore.Text.FontAsset.UpdateAtlasTexturesInQueue () (at <f4f6915fefb941f79e0deee6564d5259>:0)
UnityEngine.TextCore.Text.FontAsset.UpdateFontAssetInUpdateQueue () (at <f4f6915fefb941f79e0deee6564d5259>:0)
UnityEngine.TextCore.Text.TextGenerator.GenerateText (UnityEngine.TextCore.Text.TextGenerationSettings settings, UnityEngine.TextCore.Text.TextInfo textInfo) (at <f4f6915fefb941f79e0deee6564d5259>:0)
UnityEngine.UIElements.TextCoreHandle.Update (UnityEngine.UIElements.MeshGenerationContextUtils+TextParams parms, System.Single pixelsPerPoint) (at <13adf3fa3c294df3837c3b9a91e8b147>:0)
UnityEngine.UIElements.UIR.Implementation.UIRStylePainter.DrawTextCore (UnityEngine.UIElements.MeshGenerationContextUtils+TextParams textParams, UnityEngine.UIElements.ITextHandle handle, System.Single pixelsPerPoint) (at <13adf3fa3c294df3837c3b9a91e8b147>:0)
UnityEngine.UIElements.UIR.Implementation.UIRStylePainter.DrawText (UnityEngine.UIElements.MeshGenerationContextUtils+TextParams textParams, UnityEngine.UIElements.ITextHandle handle, System.Single pixelsPerPoint) (at <13adf3fa3c294df3837c3b9a91e8b147>:0)
UnityEngine.UIElements.MeshGenerationContextUtils.Text (UnityEngine.UIElements.MeshGenerationContext mgc, UnityEngine.UIElements.MeshGenerationContextUtils+TextParams textParams, UnityEngine.UIElements.ITextHandle handle, System.Single pixelsPerPoint) (at <13adf3fa3c294df3837c3b9a91e8b147>:0)
UnityEngine.UIElements.TextElement.OnGenerateVisualContent (UnityEngine.UIElements.MeshGenerationContext mgc) (at <13adf3fa3c294df3837c3b9a91e8b147>:0)
UnityEngine.UIElements.VisualElement.InvokeGenerateVisualContent (UnityEngine.UIElements.MeshGenerationContext mgc) (at <13adf3fa3c294df3837c3b9a91e8b147>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
```

<img width="1040" height="540" alt="Image" src="https://github.com/user-attachments/assets/eb88b3ba-a18a-4ab8-9c7c-25cf493edfe0" />

**Comment by vape** [comment]
That's strange, I thought I've fixed this bug. I'll look into it on the weekend.

**Comment by vape** [comment]
Found the issue with the sample scene, ImGui wasn't properly disposed there. Make sure to call Dispose on the `ImGui` object in your code, otherwise it will cause problems like the one you experienced, as well as memory leaks.

**Comment by GazziFX** [comment]
The problem still exists even in a blank new project

<img width="1920" height="1040" alt="Image" src="https://github.com/user-attachments/assets/a44f8f4b-98b4-4b9e-8fee-55657606dba8" />

**Comment by vape** [comment]
I cannot reproduce this on my side. Which commit are you testing on? Make sure you’ve checked out the latest `develop` branch.

**Comment by GazziFX** [comment]
Commit a0431c6a52030b4f83e72ce07cf2a3471320420b Unity 2021.3.29, and also tested with 2022.3.43

<img width="1570" height="674" alt="Image" src="https://github.com/user-attachments/assets/1523b8f1-ba8c-4b93-b676-cd78e56b7908" />

**Comment by vape** [comment]
Have you re-imported the demo scene after checking out the latest commit? Does the `DemoRoot` script you’re running include a `Dispose` call?

**Comment by GazziFX** [comment]
It is, just reenable Demo gameobject and exception occur

<img width="704" height="669" alt="Image" src="https://github.com/user-attachments/assets/3df757f6-56e5-40e9-9317-cd3507531885" />

**Comment by vape** [comment]
@GazziFX Try now

**Comment by GazziFX** [comment]
Thanks, it works. That seems strange, I also tried to call this method before and it didnt work
